// nodes1, nodes2
// links1, links2
const SampleData = {
    // 데이터 적음
    "nodes1": [
        { "id": "청소년", "value": 3, "group": "person" },
        { "id": "장면", "value": 3, "group": "media" },
        { "id": "드라마", "value": 3, "group": "media" },
        { "id": "비행", "value": 2, "group": "media" },
        { "id": "티비", "value": 4, "group": "media" },
        { "id": "폭력", "value": 1, "group": "media" },
        { "id": "사람", "value": 5, "group": "person" }
    ],
    // 데이터 많음
    "nodes2": [
        { "id": 0, "label": "Myriel", "group": 1 },
        { "id": 1, "label": "Napoleon", "group": 1 },
        { "id": 2, "label": "Mlle.Baptistine", "group": 1 },
        { "id": 3, "label": "Mme.Magloire", "group": 1 },
        { "id": 4, "label": "CountessdeLo", "group": 1 },
        { "id": 5, "label": "Geborand", "group": 1 },
        { "id": 6, "label": "Champtercier", "group": 1 },
        { "id": 7, "label": "Cravatte", "group": 1 },
        { "id": 8, "label": "Count", "group": 1 },
        { "id": 9, "label": "OldMan", "group": 1 },
        { "id": 10, "label": "Labarre", "group": 2 },
        { "id": 11, "label": "Valjean", "group": 2 },
        { "id": 12, "label": "Marguerite", "group": 3 },
        { "id": 13, "label": "Mme.deR", "group": 2 },
        { "id": 14, "label": "Isabeau", "group": 2 },
        { "id": 15, "label": "Gervais", "group": 2 },
        { "id": 16, "label": "Tholomyes", "group": 3 },
        { "id": 17, "label": "Listolier", "group": 3 },
        { "id": 18, "label": "Fameuil", "group": 3 },
        { "id": 19, "label": "Blacheville", "group": 3 },
        { "id": 20, "label": "Favourite", "group": 3 },
        { "id": 21, "label": "Dahlia", "group": 3 },
        { "id": 22, "label": "Zephine", "group": 3 },
        { "id": 23, "label": "Fantine", "group": 3 },
        { "id": 24, "label": "Mme.Thenardier", "group": 4 },
        { "id": 25, "label": "Thenardier", "group": 4 },
        { "id": 26, "label": "Cosette", "group": 5 },
        { "id": 27, "label": "Javert", "group": 4 },
        { "id": 28, "label": "Fauchelevent", "group": 0 },
        { "id": 29, "label": "Bamatabois", "group": 2 },
        { "id": 30, "label": "Perpetue", "group": 3 },
        { "id": 31, "label": "Simplice", "group": 2 },
        { "id": 32, "label": "Scaufflaire", "group": 2 },
        { "id": 33, "label": "Woman1", "group": 2 },
        { "id": 34, "label": "Judge", "group": 2 },
        { "id": 35, "label": "Champmathieu", "group": 2 },
        { "id": 36, "label": "Brevet", "group": 2 },
        { "id": 37, "label": "Chenildieu", "group": 2 },
        { "id": 38, "label": "Cochepaille", "group": 2 },
        { "id": 39, "label": "Pontmercy", "group": 4 },
        { "id": 40, "label": "Boulatruelle", "group": 6 },
        { "id": 41, "label": "Eponine", "group": 4 },
        { "id": 42, "label": "Anzelma", "group": 4 },
        { "id": 43, "label": "Woman2", "group": 5 },
        { "id": 44, "label": "MotherInnocent", "group": 0 },
        { "id": 45, "label": "Gribier", "group": 0 },
        { "id": 46, "label": "Jondrette", "group": 7 },
        { "id": 47, "label": "Mme.Burgon", "group": 7 },
        { "id": 48, "label": "Gavroche", "group": 8 },
        { "id": 49, "label": "Gillenormand", "group": 5 },
        { "id": 50, "label": "Magnon", "group": 5 },
        { "id": 51, "label": "Mlle.Gillenormand", "group": 5 },
        { "id": 52, "label": "Mme.Pontmercy", "group": 5 },
        { "id": 53, "label": "Mlle.Vaubois", "group": 5 },
        { "id": 54, "label": "Lt.Gillenormand", "group": 5 },
        { "id": 55, "label": "Marius", "group": 8 },
        { "id": 56, "label": "BaronessT", "group": 5 },
        { "id": 57, "label": "Mabeuf", "group": 8 },
        { "id": 58, "label": "Enjolras", "group": 8 },
        { "id": 59, "label": "Combeferre", "group": 8 },
        { "id": 60, "label": "Prouvaire", "group": 8 },
        { "id": 61, "label": "Feuilly", "group": 8 },
        { "id": 62, "label": "Courfeyrac", "group": 8 },
        { "id": 63, "label": "Bahorel", "group": 8 },
        { "id": 64, "label": "Bossuet", "group": 8 },
        { "id": 65, "label": "Joly", "group": 8 },
        { "id": 66, "label": "Grantaire", "group": 8 },
        { "id": 67, "label": "MotherPlutarch", "group": 9 },
        { "id": 68, "label": "Gueulemer", "group": 4 },
        { "id": 69, "label": "Babet", "group": 4 },
        { "id": 70, "label": "Claquesous", "group": 4 },
        { "id": 71, "label": "Montparnasse", "group": 4 },
        { "id": 72, "label": "Toussaint", "group": 5 },
        { "id": 73, "label": "Child1", "group": 10 },
        { "id": 74, "label": "Child2", "group": 10 },
        { "id": 75, "label": "Brujon", "group": 4 },
        { "id": 76, "label": "Mme.Hucheloup", "group": 8 }
    ],

    // 데이터 적음
    "links1": [
        { "source": "사람", "target": "장면", "value": 2 },
        { "source": "드라마", "target": "티비", "value": 4 },
        { "source": "티비", "target": "사람", "value": 6 },
        { "source": "사람", "target": "비행", "value": 8 },
        { "source": "사람", "target": "폭력", "value": 5 },
    ],
    // 데이터 많음
    "links2": [
        { "source": 1, "target": 0 },
        { "source": 2, "target": 0 },
        { "source": 3, "target": 0 },
        { "source": 3, "target": 2 },
        { "source": 4, "target": 0 },
        { "source": 5, "target": 0 },
        { "source": 6, "target": 0 },
        { "source": 7, "target": 0 },
        { "source": 8, "target": 0 },
        { "source": 9, "target": 0 },
        { "source": 11, "target": 10 },
        { "source": 11, "target": 3 },
        { "source": 11, "target": 2 },
        { "source": 11, "target": 0 },
        { "source": 12, "target": 11 },
        { "source": 13, "target": 11 },
        { "source": 14, "target": 11 },
        { "source": 15, "target": 11 },
        { "source": 17, "target": 16 },
        { "source": 18, "target": 16 },
        { "source": 18, "target": 17 },
        { "source": 19, "target": 16 },
        { "source": 19, "target": 17 },
        { "source": 19, "target": 18 },
        { "source": 20, "target": 16 },
        { "source": 20, "target": 17 },
        { "source": 20, "target": 18 },
        { "source": 20, "target": 19 },
        { "source": 21, "target": 16 },
        { "source": 21, "target": 17 },
        { "source": 21, "target": 18 },
        { "source": 21, "target": 19 },
        { "source": 21, "target": 20 },
        { "source": 22, "target": 16 },
        { "source": 22, "target": 17 },
        { "source": 22, "target": 18 },
        { "source": 22, "target": 19 },
        { "source": 22, "target": 20 },
        { "source": 22, "target": 21 },
        { "source": 23, "target": 16 },
        { "source": 23, "target": 17 },
        { "source": 23, "target": 18 },
        { "source": 23, "target": 19 },
        { "source": 23, "target": 20 },
        { "source": 23, "target": 21 },
        { "source": 23, "target": 22 },
        { "source": 23, "target": 12 },
        { "source": 23, "target": 11 },
        { "source": 24, "target": 23 },
        { "source": 24, "target": 11 },
        { "source": 25, "target": 24 },
        { "source": 25, "target": 23 },
        { "source": 25, "target": 11 },
        { "source": 26, "target": 24 },
        { "source": 26, "target": 11 },
        { "source": 26, "target": 16 },
        { "source": 26, "target": 25 },
        { "source": 27, "target": 11 },
        { "source": 27, "target": 23 },
        { "source": 27, "target": 25 },
        { "source": 27, "target": 24 },
        { "source": 27, "target": 26 },
        { "source": 28, "target": 11 },
        { "source": 28, "target": 27 },
        { "source": 29, "target": 23 },
        { "source": 29, "target": 27 },
        { "source": 29, "target": 11 },
        { "source": 30, "target": 23 },
        { "source": 31, "target": 30 },
        { "source": 31, "target": 11 },
        { "source": 31, "target": 23 },
        { "source": 31, "target": 27 },
        { "source": 32, "target": 11 },
        { "source": 33, "target": 11 },
        { "source": 33, "target": 27 },
        { "source": 34, "target": 11 },
        { "source": 34, "target": 29 },
        { "source": 35, "target": 11 },
        { "source": 35, "target": 34 },
        { "source": 35, "target": 29 },
        { "source": 36, "target": 34 },
        { "source": 36, "target": 35 },
        { "source": 36, "target": 11 },
        { "source": 36, "target": 29 },
        { "source": 37, "target": 34 },
        { "source": 37, "target": 35 },
        { "source": 37, "target": 36 },
        { "source": 37, "target": 11 },
        { "source": 37, "target": 29 },
        { "source": 38, "target": 34 },
        { "source": 38, "target": 35 },
        { "source": 38, "target": 36 },
        { "source": 38, "target": 37 },
        { "source": 38, "target": 11 },
        { "source": 38, "target": 29 },
        { "source": 39, "target": 25 },
        { "source": 40, "target": 25 },
        { "source": 41, "target": 24 },
        { "source": 41, "target": 25 },
        { "source": 42, "target": 41 },
        { "source": 42, "target": 25 },
        { "source": 42, "target": 24 },
        { "source": 43, "target": 11 },
        { "source": 43, "target": 26 },
        { "source": 43, "target": 27 },
        { "source": 44, "target": 28 },
        { "source": 44, "target": 11 },
        { "source": 45, "target": 28 },
        { "source": 47, "target": 46 },
        { "source": 48, "target": 47 },
        { "source": 48, "target": 25 },
        { "source": 48, "target": 27 },
        { "source": 48, "target": 11 },
        { "source": 49, "target": 26 },
        { "source": 49, "target": 11 },
        { "source": 50, "target": 49 },
        { "source": 50, "target": 24 },
        { "source": 51, "target": 49 },
        { "source": 51, "target": 26 },
        { "source": 51, "target": 11 },
        { "source": 52, "target": 51 },
        { "source": 52, "target": 39 },
        { "source": 53, "target": 51 },
        { "source": 54, "target": 51 },
        { "source": 54, "target": 49 },
        { "source": 54, "target": 26 },
        { "source": 55, "target": 51 },
        { "source": 55, "target": 49 },
        { "source": 55, "target": 39 },
        { "source": 55, "target": 54 },
        { "source": 55, "target": 26 },
        { "source": 55, "target": 11 },
        { "source": 55, "target": 16 },
        { "source": 55, "target": 25 },
        { "source": 55, "target": 41 },
        { "source": 55, "target": 48 },
        { "source": 56, "target": 49 },
        { "source": 56, "target": 55 },
        { "source": 57, "target": 55 },
        { "source": 57, "target": 41 },
        { "source": 57, "target": 48 },
        { "source": 58, "target": 55 },
        { "source": 58, "target": 48 },
        { "source": 58, "target": 27 },
        { "source": 58, "target": 57 },
        { "source": 58, "target": 11 },
        { "source": 59, "target": 58 },
        { "source": 59, "target": 55 },
        { "source": 59, "target": 48 },
        { "source": 59, "target": 57 },
        { "source": 60, "target": 48 },
        { "source": 60, "target": 58 },
        { "source": 60, "target": 59 },
        { "source": 61, "target": 48 },
        { "source": 61, "target": 58 },
        { "source": 61, "target": 60 },
        { "source": 61, "target": 59 },
        { "source": 61, "target": 57 },
        { "source": 61, "target": 55 },
        { "source": 62, "target": 55 },
        { "source": 62, "target": 58 },
        { "source": 62, "target": 59 },
        { "source": 62, "target": 48 },
        { "source": 62, "target": 57 },
        { "source": 62, "target": 41 },
        { "source": 62, "target": 61 },
        { "source": 62, "target": 60 },
        { "source": 63, "target": 59 },
        { "source": 63, "target": 48 },
        { "source": 63, "target": 62 },
        { "source": 63, "target": 57 },
        { "source": 63, "target": 58 },
        { "source": 63, "target": 61 },
        { "source": 63, "target": 60 },
        { "source": 63, "target": 55 },
        { "source": 64, "target": 55 },
        { "source": 64, "target": 62 },
        { "source": 64, "target": 48 },
        { "source": 64, "target": 63 },
        { "source": 64, "target": 58 },
        { "source": 64, "target": 61 },
        { "source": 64, "target": 60 },
        { "source": 64, "target": 59 },
        { "source": 64, "target": 57 },
        { "source": 64, "target": 11 },
        { "source": 65, "target": 63 },
        { "source": 65, "target": 64 },
        { "source": 65, "target": 48 },
        { "source": 65, "target": 62 },
        { "source": 65, "target": 58 },
        { "source": 65, "target": 61 },
        { "source": 65, "target": 60 },
        { "source": 65, "target": 59 },
        { "source": 65, "target": 57 },
        { "source": 65, "target": 55 },
        { "source": 66, "target": 64 },
        { "source": 66, "target": 58 },
        { "source": 66, "target": 59 },
        { "source": 66, "target": 62 },
        { "source": 66, "target": 65 },
        { "source": 66, "target": 48 },
        { "source": 66, "target": 63 },
        { "source": 66, "target": 61 },
        { "source": 66, "target": 60 },
        { "source": 67, "target": 57 },
        { "source": 68, "target": 25 },
        { "source": 68, "target": 11 },
        { "source": 68, "target": 24 },
        { "source": 68, "target": 27 },
        { "source": 68, "target": 48 },
        { "source": 68, "target": 41 },
        { "source": 69, "target": 25 },
        { "source": 69, "target": 68 },
        { "source": 69, "target": 11 },
        { "source": 69, "target": 24 },
        { "source": 69, "target": 27 },
        { "source": 69, "target": 48 },
        { "source": 69, "target": 41 },
        { "source": 70, "target": 25 },
        { "source": 70, "target": 69 },
        { "source": 70, "target": 68 },
        { "source": 70, "target": 11 },
        { "source": 70, "target": 24 },
        { "source": 70, "target": 27 },
        { "source": 70, "target": 41 },
        { "source": 70, "target": 58 },
        { "source": 71, "target": 27 },
        { "source": 71, "target": 69 },
        { "source": 71, "target": 68 },
        { "source": 71, "target": 70 },
        { "source": 71, "target": 11 },
        { "source": 71, "target": 48 },
        { "source": 71, "target": 41 },
        { "source": 71, "target": 25 },
        { "source": 72, "target": 26 },
        { "source": 72, "target": 27 },
        { "source": 72, "target": 11 },
        { "source": 73, "target": 48 },
        { "source": 74, "target": 48 },
        { "source": 74, "target": 73 },
        { "source": 75, "target": 69 },
        { "source": 75, "target": 68 },
        { "source": 75, "target": 25 },
        { "source": 75, "target": 48 },
        { "source": 75, "target": 41 },
        { "source": 75, "target": 70 },
        { "source": 75, "target": 71 },
        { "source": 76, "target": 64 },
        { "source": 76, "target": 65 },
        { "source": 76, "target": 66 },
        { "source": 76, "target": 63 },
        { "source": 76, "target": 62 },
        { "source": 76, "target": 48 },
        { "source": 76, "target": 58 },
    ]
}